@tool
extends EditorScenePostImport

# AUTO-GENERATED by the Tesana engine.
# Do not edit by hand -- regenerated each time a character is downloaded.
#
# Character GLBs ship with a coordinate convention whose visible front
# lands at +Z. This script applies a +PI Y rotation to the imported scene
# root so the BAKED PackedScene's mesh actually faces -Z (Godot's
# Vector3.MODEL_FRONT, what look_at() and atan2(-dx, -dz) both expect).
# Because the rotation is baked at IMPORT time (not at runtime), game
# code never has to remember a magic flip -- loading the .glb just
# produces a correctly-oriented character.

func _post_import(scene: Node) -> Object:
	if scene is Node3D:
		(scene as Node3D).rotation.y = PI
	return scene
