extends CanvasLayer

# AUTO-GENERATED by sdk/game_engine/provisioning/loading_screen.py.
# Do NOT edit by hand -- regenerated on every build from the canonical
# template. Per-game theming flows through res://assets/ui/theme.tres
# (ProgressBar/fill stylebox color), so Claude's creative control over
# the bar accent works without touching this file.
#
# Layout rules baked in (see .claude/skills/godot-loading-screen):
#   R1: wordmark uses explicit anchors symmetric around 0.5
#   R2: bottom band anchored to viewport bottom with NEGATIVE offset_top
#   R3: autoload owns PRELOAD_PATHS + _cache + _busy + calls
#       change_scene_to_packed (not _to_file)

# Filled in at engine provisioning time by walking the game's assets/ and
# scenes/. Ordered small/fast -> big/slow so the bar fills smoothly as
# the slower assets land at the end.
const PRELOAD_PATHS: PackedStringArray = [
	# -- Scenes --
	"res://scenes/game_world.tscn",
	"res://scenes/main.tscn",
	"res://scenes/ui/main_menu.tscn",
	# -- UI / textures / themes / fonts --
	"res://assets/fonts/special_elite.ttf",
	"res://assets/ui/btn_main.png",
	"res://assets/ui/btn_main.tres",
	"res://assets/ui/loading_bar_accent.tres",
	"res://assets/ui/loading_screen.png",
	"res://assets/ui/panel_main.png",
	"res://assets/ui/panel_main.tres",
	"res://assets/ui/theme.tres",
	"res://assets/ui/title_poster.webp",
	"res://assets/ui/title_poster_sm.webp",
	"res://assets/ui/wordmark_title.png",
	# -- World textures --
	"res://assets/textures/backgrounds/menu_void_corridor.png",
	"res://assets/textures/floors/backrooms_carpet_clean.png",
	"res://assets/textures/floors/backrooms_linoleum.png",
	"res://assets/textures/surfaces/backrooms_ceiling_tiles.png",
	"res://assets/textures/walls/backrooms_yellow_wallpaper.png",
	# -- Audio (music, SFX, ambient) --
	"res://assets/audio/ambient/ambient_backrooms_office_fluorescent_hum_loop.mp3",
	"res://assets/audio/ambient/ambient_empty_building_hvac_drone_loop.mp3",
	"res://assets/audio/music/music_climax_final_exit_drone.mp3",
	"res://assets/audio/ambient/ambient.mp3",
	"res://assets/audio/sfx/enemy/enemy_chase_distorted_scream.mp3",
	"res://assets/audio/sfx/enemy/enemy_close_breath.mp3",
	"res://assets/audio/sfx/enemy/enemy_entity_heavy_steps.mp3",
	"res://assets/audio/sfx/enemy/enemy_jumpscare_scream.mp3",
	"res://assets/audio/sfx/environment/environment_ceiling_drag.mp3",
	"res://assets/audio/sfx/environment/environment_distant_door_slam.mp3",
	"res://assets/audio/sfx/environment/environment_distant_footsteps_echo.mp3",
	"res://assets/audio/sfx/environment/environment_hallway_rearrange_creak.mp3",
	"res://assets/audio/sfx/environment/environment_light_flicker_buzz.mp3",
	"res://assets/audio/sfx/environment/environment_phone_ring_twice.mp3",
	"res://assets/audio/sfx/pickup/pickup_escape_unlocked.mp3",
	"res://assets/audio/sfx/pickup/pickup_snus_pickup.mp3",
	"res://assets/audio/sfx/player/player_player_step_carpet.mp3",
	# -- 3D models + animation libs (load last) --
	"res://assets/animations/humanoid_profile_bone_map.tres",
	"res://assets/characters/survivor_body/player.fbx",
	"res://assets/characters/survivor_body/survivor_body.glb",
	"res://assets/characters/survivor_body/survivor_body_animations.tres",
	"res://assets/characters/watcher_silhouette/watcher_silhouette.glb",
	"res://assets/characters/watcher_silhouette/watcher_silhouette_animations.tres",
	"res://assets/environment/interiors/yellow_corner_l.glb",
	"res://assets/environment/interiors/yellow_corridor_segment.glb",
	"res://assets/environment/interiors/yellow_room_deadend.glb",
	"res://assets/props/decorations/desk_phone_offhook.glb",
	"res://assets/props/decorations/exit_door_real.glb",
	"res://assets/props/decorations/exit_sign_hanging.glb",
	"res://assets/props/decorations/fluorescent_tube_fixture.glb",
	"res://assets/props/decorations/office_door_closed.glb",
	"res://assets/props/decorations/wet_floor_sign.glb",
	"res://assets/props/furniture/broken_office_chair.glb",
	"res://assets/props/items/SNUS.glb",
]

# DEFAULT_ACCENT is the fallback bar-fill color when assets/ui/theme.tres
# doesn't ship a ProgressBar/fill stylebox. Picked to look reasonable on
# a black background.
const DEFAULT_ACCENT := Color(0.96, 0.70, 0.45, 1.0)
const DEFAULT_BG := Color(0.08, 0.08, 0.10, 0.85)

var _cache: Dictionary = {}
var _preloaded: bool = false
var _busy: bool = false
var _vfx_warmed: bool = false

var _root: Control
var _progress: ProgressBar
var _status: Label


func _ready() -> void:
	layer = 100
	process_mode = Node.PROCESS_MODE_ALWAYS
	visible = false
	_build_ui()


# Per-game accent resolution. Three lookups in priority order:
#
#  1. assets/ui/loading_bar_accent.tres  -- a StyleBoxFlat written by
#     Claude after generate_ui_kit, with bg_color matching the kit's
#     accent. This is the primary mechanism (see godot-loading-screen
#     skill).
#
#  2. assets/ui/theme.tres "ProgressBar/styles/fill" stylebox --
#     forward-compat for when/if generate_ui_kit ever synthesizes a
#     ProgressBar slot directly. Currently it doesn't, so this branch
#     is dormant but kept so a future upstream change Just Works.
#
#  3. DEFAULT_ACCENT -- neutral fallback when neither file is present
#     (e.g. a game that skipped the UI kit step).
func _resolve_accent() -> Color:
	if ResourceLoader.exists("res://assets/ui/loading_bar_accent.tres"):
		var sb := load("res://assets/ui/loading_bar_accent.tres") as StyleBoxFlat
		if sb:
			return sb.bg_color
	if ResourceLoader.exists("res://assets/ui/theme.tres"):
		var t := load("res://assets/ui/theme.tres") as Theme
		if t:
			var fill := t.get_stylebox("fill", "ProgressBar") as StyleBoxFlat
			if fill:
				return fill.bg_color
	return DEFAULT_ACCENT


func _build_ui() -> void:
	_root = Control.new()
	add_child(_root)
	_root.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	_root.mouse_filter = Control.MOUSE_FILTER_IGNORE

	# Dark atmospheric field for tension.
	var bg := ColorRect.new()
	bg.color = Color(0.05, 0.05, 0.06, 1.0)
	_root.add_child(bg)
	bg.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)

	# Kept as a non-rendered compatibility target for the VFX warm-up path.
	_status = Label.new()
	_status.visible = false
	_root.add_child(_status)

	_progress = ProgressBar.new()
	_progress.min_value = 0.0
	_progress.max_value = 1.0
	_progress.show_percentage = false
	_root.add_child(_progress)
	_progress.anchor_left = 0.08
	_progress.anchor_right = 0.43
	_progress.anchor_top = 0.88
	_progress.anchor_bottom = 0.88
	_progress.offset_top = -1.0
	_progress.offset_bottom = 1.0
	var pb_bg := StyleBoxFlat.new()
	pb_bg.bg_color = Color(0.15, 0.15, 0.17, 1.0)
	var pb_fill := StyleBoxFlat.new()
	pb_fill.bg_color = Color(0.85, 0.70, 0.40, 1.0)
	_progress.add_theme_stylebox_override("background", pb_bg)
	_progress.add_theme_stylebox_override("fill", pb_fill)


func _show() -> void:
	visible = true
	set_progress(0.0)


func _hide() -> void:
	visible = false


func set_progress(p: float) -> void:
	if _progress:
		_progress.value = clamp(p, 0.0, 1.0)
	if _status:
		_status.text = "Loading... %d%%" % int(p * 100.0)


# Heavy first-time warm-up. Honors a min_display floor so quick loads
# still show the screen long enough for the player to read.
func preload_and_change_scene(scene_path: String, min_display: float = 1.5) -> void:
	if _busy:
		_hide()
		_busy = false
	_busy = true
	_show()
	var tree := get_tree()
	if tree:
		tree.create_timer(3.2).timeout.connect(func():
			_hide()
			_busy = false
		)
	var t0 := Time.get_ticks_msec()
	await get_tree().process_frame
	await get_tree().process_frame  # double-frame render guarantee
	if not _preloaded:
		await _run_preload_sequence()  # fills 0% -> 92%
		_preloaded = true
	await _change_scene_to(scene_path)  # fills 92% -> 100%
	await _vfx_warmup()  # 3D-web: pre-compile VFX shaders while overlay covers the view
	var elapsed := float(Time.get_ticks_msec() - t0) / 1000.0
	if elapsed < min_display:
		await get_tree().create_timer(min_display - elapsed).timeout
	_hide()
	_busy = false


# Fast subsequent transition. Uses the cached PackedScene if it was
# warmed in the first preload pass; otherwise falls back to a fresh load.
func change_scene(scene_path: String, min_display: float = 0.6) -> void:
	if _busy:
		_hide()
		_busy = false
	_busy = true
	_show()
	var tree := get_tree()
	if tree:
		tree.create_timer(3.2).timeout.connect(func():
			_hide()
			_busy = false
		)
	var t0 := Time.get_ticks_msec()
	await get_tree().process_frame
	await get_tree().process_frame
	await _change_scene_to(scene_path)
	var elapsed := float(Time.get_ticks_msec() - t0) / 1000.0
	if elapsed < min_display:
		await get_tree().create_timer(min_display - elapsed).timeout
	_hide()
	_busy = false


# Synchronous load() per asset with a process_frame yield between each
# iteration. We deliberately do NOT use ResourceLoader.load_threaded_*
# here -- on single-threaded web (Godot 4's default web export, which
# is what most Tesana games target), there is no background thread, so
# load_threaded_get_status returns THREAD_LOAD_LOADED immediately on
# the first poll. The inner `while` loop then breaks BEFORE any
# `await get_tree().process_frame`, the whole 50+ iteration sequence
# runs in a single frame, and the bar appears to jump from 0% to 92%
# in one paint -- exactly the symptom that motivated threading in the
# first place.
#
# The simpler synchronous pattern below yields one frame per asset
# (independent of cache hits / missing files / load() runtime), so the
# bar repaints smoothly on EVERY web export configuration. For
# multi-threaded web with SharedArrayBuffer the per-asset frame yield
# is the only thing the bar cares about anyway -- you don't gain
# meaningful parallelism on the main thread that owns the renderer.
func _run_preload_sequence() -> void:
	var total := PRELOAD_PATHS.size()
	if total == 0:
		set_progress(0.92)
		return
	for i in total:
		var path := PRELOAD_PATHS[i]
		if _cache.has(path) or not ResourceLoader.exists(path):
			set_progress(float(i + 1) / float(total) * 0.92)
			await get_tree().process_frame
			continue
		var res := load(path)
		if res:
			_cache[path] = res
		else:
			push_warning("LoadingScreen preload failed: " + path)
		# Reserve the last 8% for the actual scene swap.
		set_progress(float(i + 1) / float(total) * 0.92)
		await get_tree().process_frame


func _change_scene_to(scene_path: String) -> void:
	var packed := _cache.get(scene_path) as PackedScene
	if packed:
		get_tree().change_scene_to_packed(packed)
	else:
		get_tree().change_scene_to_file(scene_path)
	set_progress(1.0)
	await get_tree().process_frame
	await get_tree().process_frame


# 3D-web VFX shader pre-compile.
#
# Godot compiles a material/shader variant the first time the renderer DRAWS
# it -- NOT when the resource is load()ed. The VFX root scenes are already
# warm in _cache (the asset walker lists every assets/3d_vfx/.../effects/*.tscn
# in PRELOAD_PATHS), but their shaders are still uncompiled. So the FIRST time
# an effect spawns in gameplay the main thread stalls ~150-300ms on
# single-threaded web while variants compile -- the "first explosion freezes
# the game" stutter.
#
# Fix: instance each VFX root ONCE, in front of the active camera so the
# renderer actually draws it (off-screen would not trigger compilation), let
# it render two frames, then free it. The full-screen loading overlay (this
# CanvasLayer, layer=100) hides the flash; the 3D pass still renders
# underneath, so the variants compile. Runs once, on the heavy first load,
# web + 3D only. Source of truth is PRELOAD_PATHS filtered to 3d_vfx effect
# roots -- no separate manifest needed.
func _vfx_warmup() -> void:
	if _vfx_warmed:
		return
	_vfx_warmed = true
	if not OS.has_feature("web"):
		return  # the first-draw stutter only manifests on single-threaded web
	var scene := get_tree().current_scene
	var cam := get_viewport().get_camera_3d()
	if scene == null or cam == null:
		return  # 2D game / no active 3D camera -> nothing to warm
	var vfx_paths: Array[String] = []
	for p in PRELOAD_PATHS:
		if p.ends_with(".tscn") and ("/3d_vfx/" in p) and ("/effects/" in p):
			vfx_paths.append(p)
	if vfx_paths.is_empty():
		return
	_status.text = "Preparing effects..."
	# Invisible holder in the current scene so effects compile against the real
	# light / fog / tonemap environment they will actually be used in.
	var holder := Node3D.new()
	scene.add_child(holder)
	var spawn_at := cam.global_position - cam.global_transform.basis.z * 3.0
	for path in vfx_paths:
		var ps := _cache.get(path) as PackedScene
		if ps == null and ResourceLoader.exists(path):
			ps = load(path) as PackedScene
		if ps == null:
			continue
		var inst: Node = ps.instantiate()
		# Same guards use_3d_vfx bakes in -- without them an effect with no
		# AnimationPlayer recurses to a stack overflow on add_child, and
		# proximity_fade renders invisible in GL Compatibility.
		if "autoplay" in inst:
			inst.set("autoplay", false)
		if "proximity_fade" in inst:
			inst.set("proximity_fade", false)
		holder.add_child(inst)
		if inst is Node3D:
			inst.global_position = spawn_at  # in frustum -> drawn -> shader compiled
		if inst.has_node("AnimationPlayer") and inst.has_method("play"):
			inst.call("play")
		await get_tree().process_frame
		await get_tree().process_frame
		if is_instance_valid(inst):
			inst.queue_free()
	if is_instance_valid(holder):
		holder.queue_free()
